"use client";

import { useRef, useEffect, useState, useCallback } from 'react';

// ──────────────────────────────────────────────
// Config — matches the sprite sheet generated by process_diamond.py
// ──────────────────────────────────────────────
const COLS = 10;
const ROWS = 19;
const TOTAL_FRAMES = 184;
const DEFAULT_FPS = 24;  // 184 real frames @ 24fps = ~7.7s per rotation

/**
 * DiamondSprite — Pre-rendered frame-sequence diamond rotation.
 * 
 * Replaces the Three.js Canvas with a lightweight sprite sheet animation.
 * Loads a single PNG sprite sheet and draws frames on a canvas element.
 * 
 * Props:
 *   - reverse: boolean — play frames in reverse (counter-clockwise)
 *   - fps: number — playback speed (default: 15)
 *   - paused: boolean — pause the animation
 *   - className: string — optional CSS class
 */
export default function DiamondSprite({ 
  reverse = true,   // counter-clockwise by default
  fps = DEFAULT_FPS, 
  paused = false,
  className = '' 
}) {
  const canvasRef = useRef(null);
  const spriteRef = useRef(null);
  const frameRef = useRef(0);
  const rafRef = useRef(null);
  const lastTimeRef = useRef(0);
  const [loaded, setLoaded] = useState(false);

  // Load sprite sheet
  useEffect(() => {
    const img = new Image();
    img.src = '/diamond-spritesheet.webp';
    img.onload = () => {
      spriteRef.current = img;
      setLoaded(true);
    };
    img.onerror = () => {
      console.error('DiamondSprite: Failed to load sprite sheet');
    };
  }, []);

  // Animation loop using requestAnimationFrame for smooth rendering
  const animate = useCallback((timestamp) => {
    if (paused || !spriteRef.current || !canvasRef.current) {
      rafRef.current = requestAnimationFrame(animate);
      return;
    }

    const elapsed = timestamp - lastTimeRef.current;
    const frameInterval = 1000 / fps;

    if (elapsed >= frameInterval) {
      lastTimeRef.current = timestamp - (elapsed % frameInterval);

      const canvas = canvasRef.current;
      const ctx = canvas.getContext('2d');
      const sprite = spriteRef.current;

      const frameW = sprite.naturalWidth / COLS;
      const frameH = sprite.naturalHeight / ROWS;

      const frame = frameRef.current;
      const col = frame % COLS;
      const row = Math.floor(frame / COLS);

      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(
        sprite,
        col * frameW, row * frameH, frameW, frameH,
        0, 0, canvas.width, canvas.height
      );

      // Advance frame
      if (reverse) {
        frameRef.current = (frame - 1 + TOTAL_FRAMES) % TOTAL_FRAMES;
      } else {
        frameRef.current = (frame + 1) % TOTAL_FRAMES;
      }
    }

    rafRef.current = requestAnimationFrame(animate);
  }, [fps, paused, reverse]);

  useEffect(() => {
    if (!loaded) return;
    rafRef.current = requestAnimationFrame(animate);
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
    };
  }, [loaded, animate]);

  return (
    <canvas
      ref={canvasRef}
      width={500}
      height={500}
      className={className}
      style={{
        width: '100%',
        height: '100%',
        objectFit: 'contain',
        opacity: loaded ? 1 : 0,
        transition: 'opacity 0.6s ease',
      }}
    />
  );
}
